rebvo:
  global:
    VideoNetEnabled: true
    VideoNetHost: 127.0.0.1
    VideoNetPort: 2708
    BlockingUDP: false
    SaveLog: true
    LogFile: rebvo_log.m
    TrayFile: rebvo_tray.txt

  Camera:
    ZfX: 440.00771082333284
    ZfY: 436.87623404762235
    PPx: 323.2234196809038
    PPy: 232.64389679764312
    KcR2: -0.35634944490941167
    KcR4: 0.10342986450079168
    KcR6: 0
    KcP1: 0.0
    KcP2: 0.0
    ImageWidth: 640
    ImageHeight: 480
    FPS: 30
    UseUndistort: false
    Rotate180: false

  imu:
    transCam2Imu: [0.0250, 0.0060, 0.0]
    rotCam2Imu:   [1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]
    ImuMode: 2
    SampleTime: 0.0058823529411764705
    TimeDesinc: 0
    InitBias: true
    InitBiasFrameNum: 300
    BiasHintX: 0.0188
    BiasHintY: 0.0037
    BiasHintZ: 0.0776
    g_module: 9.8
    GiroMeasStdDev: 0.0012
    GiroBiasStdDev: 0.000174
    AcelMeasStdDev: 0.04
    g_module_uncer: 0.2e3
    g_uncert: 2e-3
    VBiasStdDev: 1e-7
    CircBufferSize: 1000
    ScaleStdDevMult: 1e+5
    ScaleStdDevMax: 1e-4
    ScaleStdDevInit: 1.2e-5


  Detector:
    Sigma0: 8.56359
    KSigma: 1.2599
    ReferencePoints: 20000
    MaxPoints: 50000
    TrackPoints: 17000
    DetectorThresh: 0.001
    DetectorAutoGain: 5e-7
    DetectorMaxThresh: 0.5
    DetectorMinThresh: 0.005
    DetectorPlaneFitSize: 2
    DetectorPosNegThresh: 0.4
    DetectorDoGThresh: 0.095259868922420

  TrackMaper:

    SearchRange: 40
    QCutOffNumBins: 100
    QCutOffQuantile: 0.9
    TrackerIterNum: 5
    TrackerInitType: 0
    TrackerInitIterNum: 2
    TrackerMatchThresh: 0.5
    MatchThreshModule: 1
    MatchThreshAngle: 45
    MatchNumThresh: 0
    ReweigthDistance: 5
    RegularizeThresh: 0.5
    LocationUncertaintyMatch: 2
    ReshapeQAbsolute: 1e-4
    ReshapeQRelative: 1.6968e-04
    LocationUncertainty: 1
    DoReScaling: false
    GlobalMatchThreshold: 1500

  ProcesorConfig:
    SetAffinity: true
    CamaraT1: 1
    CamaraT2: 2
    CamaraT3: 3
